language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
- PHPUNIT_VERSION=4.8.*
- PHPUNIT_VERSION=5.7.*
- PHPUNIT_VERSION=^6.0

matrix:
  exclude:
    - php: 5.5
      env: PHPUNIT_VERSION=5.7.*
    - php: 5.5
      env: PHPUNIT_VERSION=^6.0
    - php: 5.6
      env: PHPUNIT_VERSION=^6.0

cache:
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
  - composer require --prefer-source --dev phpunit/phpunit:${PHPUNIT_VERSION}

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover